/**
 * Thermal inspection report export — PDF (via jsPDF) and RTF (custom writer
 * with embedded PNG images).
 */

import type { ThermalReport, ReportAnomalyEntry, ReportImageEntry } from '@/types/thermal';
import { CLASSIFICATION_LABELS } from '@/types/thermal';

declare const __APP_VERSION__: string;

export interface ReportImages {
  /** entry.id → { thermal, visual } data URLs (PNG/JPEG) */
  [entryId: string]: { thermal: string | null; visual: string | null };
}

/** Extra embeddable content resolved at export time. */
export interface ReportExtras {
  /** PNG data URL of the embedded Metashape orthomosaic preview. */
  orthoDataUrl?: string | null;
  /** Caption for the orthomosaic (file name, dimensions, CRS). */
  orthoLabel?: string;
  /** height/width of the orthomosaic — preserves the true aspect ratio. */
  orthoAspect?: number;
}

function fmtDuration(secs: number | null): string {
  if (secs == null || Number.isNaN(secs)) return '—';
  const total = Math.round(secs);
  const m = Math.floor(total / 60);
  const s = total % 60;
  return m > 0 ? `${m}m ${s}s` : `${s}s`;
}

function fmtMeters(m: number | null): string {
  if (m == null || Number.isNaN(m)) return '—';
  return m >= 1000 ? `${(m / 1000).toFixed(2)} km` : `${m.toFixed(0)} m`;
}

const SEVERITY_LABELS: Record<string, string> = {
  low: 'Low',
  medium: 'Medium',
  high: 'High',
};

function fmtTemp(t: number | null): string {
  return t == null || Number.isNaN(t) ? '—' : `${t.toFixed(1)} °C`;
}

function fmtGps(lat: number | null, lon: number | null): string {
  if (lat == null || lon == null) return '—';
  return `${lat.toFixed(6)}, ${lon.toFixed(6)}`;
}

function appVersion(): string {
  try {
    return __APP_VERSION__;
  } catch {
    return '';
  }
}

// ============================================================================
// PDF export
// ============================================================================

export async function buildReportPdf(
  report: ThermalReport,
  images: ReportImages,
  extras: ReportExtras = {},
): Promise<Uint8Array> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 16;
  const contentW = pageW - margin * 2;
  let y = margin;

  const checkPage = (needed: number) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const heading = (text: string, size = 13) => {
    checkPage(12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(size);
    doc.setTextColor(20, 60, 110);
    doc.text(text, margin, y);
    y += 2;
    doc.setDrawColor(20, 60, 110);
    doc.setLineWidth(0.4);
    doc.line(margin, y, margin + contentW, y);
    y += 6;
    doc.setTextColor(0, 0, 0);
  };

  const paragraph = (text: string, size = 10) => {
    if (!text.trim()) return;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(size);
    const lines = doc.splitTextToSize(text, contentW) as string[];
    for (const line of lines) {
      checkPage(6);
      doc.text(line, margin, y);
      y += 5;
    }
    y += 2;
  };

  const kv = (key: string, value: string) => {
    checkPage(6);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(`${key}:`, margin, y);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(value || '—', contentW - 48) as string[];
    doc.text(lines, margin + 48, y);
    y += Math.max(5, lines.length * 5);
  };

  // ---- Title ----
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(19);
  doc.setTextColor(20, 60, 110);
  doc.text('Thermal Inspection Report', margin, y + 4);
  y += 12;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(110, 110, 110);
  doc.text(
    `Generated by Open DroneLog${appVersion() ? ` v${appVersion()}` : ''} · DJI Thermal SDK`,
    margin,
    y,
  );
  doc.setTextColor(0, 0, 0);
  y += 8;

  let sec = 1;

  // ---- Header data ----
  heading(`${sec++}. Header Data`);
  kv('Property Address', report.propertyAddress);
  kv('Inspection Date', report.inspectionDate);
  kv('Weather Conditions', report.weatherConditions);
  kv('Inspector Name', report.inspectorName);
  y += 3;

  if (report.summary.trim()) {
    heading(`${sec++}. Summary`);
    paragraph(report.summary);
  }

  // ---- Linked DJI flight operations ----
  if ((report.linkedFlights ?? []).length > 0) {
    heading(`${sec++}. Flight Operations (DJI)`);
    for (const f of report.linkedFlights) {
      checkPage(14);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text(f.displayName || `Flight ${f.id}`, margin, y);
      y += 5;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      const details = [
        f.startTime ? `Date: ${f.startTime}` : null,
        f.droneModel ? `Drone: ${f.droneModel}${f.aircraftName ? ` (${f.aircraftName})` : ''}` : null,
        `Duration: ${fmtDuration(f.durationSecs)}`,
        `Distance: ${fmtMeters(f.totalDistance)}`,
        f.maxAltitude != null ? `Max altitude: ${f.maxAltitude.toFixed(0)} m` : null,
        f.maxSpeed != null ? `Max speed: ${f.maxSpeed.toFixed(1)} m/s` : null,
        f.homeLat != null && f.homeLon != null
          ? `Home: ${f.homeLat.toFixed(6)}, ${f.homeLon.toFixed(6)}`
          : null,
        f.photoCount != null ? `Photos: ${f.photoCount}` : null,
      ]
        .filter(Boolean)
        .join('  ·  ');
      const lines = doc.splitTextToSize(details, contentW) as string[];
      for (const line of lines) {
        checkPage(5);
        doc.text(line, margin, y);
        y += 4.2;
      }
      y += 3;
    }
  }

  // ---- Metashape orthomosaic ----
  if (extras.orthoDataUrl || report.orthomosaicLink.trim()) {
    heading(`${sec++}. Orthomosaic (Agisoft Metashape)`);
    if (extras.orthoDataUrl) {
      const aspect = extras.orthoAspect && extras.orthoAspect > 0 ? extras.orthoAspect : 0.66;
      let imgW = contentW;
      let imgH = imgW * aspect;
      const maxH = pageH - margin * 2 - 24;
      if (imgH > maxH) {
        imgH = maxH;
        imgW = imgH / aspect;
      }
      checkPage(imgH + 14);
      try {
        const x = margin + (contentW - imgW) / 2;
        doc.addImage(extras.orthoDataUrl, 'PNG', x, y, imgW, imgH, undefined, 'FAST');
        y += imgH + 3;
      } catch {
        // embed is best-effort
      }
      if (extras.orthoLabel) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(110, 110, 110);
        checkPage(5);
        doc.text(extras.orthoLabel, margin, y);
        doc.setTextColor(0, 0, 0);
        y += 6;
      }
    }
    if (report.orthomosaicLink.trim()) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(20, 90, 200);
      checkPage(6);
      doc.textWithLink(report.orthomosaicLink, margin, y, { url: report.orthomosaicLink });
      doc.setTextColor(0, 0, 0);
      y += 7;
    }
  }

  // ---- Imaging log / comparative matrix ----
  heading(`${sec++}. Thermal Imaging Log & Comparative Matrix`);
  if (report.imagingLog.length === 0) {
    paragraph('No imaging entries.');
  }
  for (let i = 0; i < report.imagingLog.length; i++) {
    const entry = report.imagingLog[i];
    const imgPair = images[entry.id] ?? { thermal: null, visual: null };
    const colW = (contentW - 6) / 2;
    const imgH = colW * 0.75;
    checkPage(imgH + 26);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(`${i + 1}. ${entry.caption || 'Imaging pair'}`, margin, y);
    y += 5;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(110, 110, 110);
    doc.text('Visual (Zoom/Wide)', margin, y);
    doc.text('Thermal (Infrared)', margin + colW + 6, y);
    doc.setTextColor(0, 0, 0);
    y += 2;

    const drawImg = (dataUrl: string | null, x: number) => {
      if (dataUrl) {
        try {
          const fmt = dataUrl.startsWith('data:image/png') ? 'PNG' : 'JPEG';
          doc.addImage(dataUrl, fmt, x, y, colW, imgH, undefined, 'FAST');
        } catch {
          doc.setDrawColor(180, 180, 180);
          doc.rect(x, y, colW, imgH);
        }
      } else {
        doc.setDrawColor(180, 180, 180);
        doc.rect(x, y, colW, imgH);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('No image', x + colW / 2 - 8, y + imgH / 2);
        doc.setTextColor(0, 0, 0);
      }
    };
    drawImg(imgPair.visual, margin);
    drawImg(imgPair.thermal, margin + colW + 6);
    y += imgH + 4;

    if (entry.lrfData.trim()) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text('LRF / Range Data: ', margin, y);
      doc.setFont('helvetica', 'normal');
      const lines = doc.splitTextToSize(entry.lrfData, contentW - 30) as string[];
      doc.text(lines, margin + 30, y);
      y += Math.max(4, lines.length * 4);
    }
    y += 4;
  }

  // ---- Anomaly log ----
  heading(`${sec++}. Thermal Anomaly Log`);
  if (report.anomalies.length === 0) {
    paragraph('No anomalies recorded.');
  } else {
    // Table header
    const cols = [
      { label: 'ID', w: 14 },
      { label: 'Location / Geotag', w: 44 },
      { label: 'T max', w: 18 },
      { label: 'T min', w: 18 },
      { label: 'Baseline', w: 20 },
      // 'dT': jsPDF's built-in WinAnsi fonts cannot encode Δ (U+0394)
      { label: 'dT', w: 10 },
      { label: 'Severity', w: 15 },
      { label: 'Classification', w: 39 },
    ];
    const drawTableHeader = () => {
      doc.setFillColor(20, 60, 110);
      doc.rect(margin, y - 4, contentW, 6, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(255, 255, 255);
      let x = margin + 1.5;
      for (const c of cols) {
        doc.text(c.label, x, y);
        x += c.w;
      }
      doc.setTextColor(0, 0, 0);
      y += 5;
    };
    checkPage(20);
    drawTableHeader();
    doc.setFont('helvetica', 'normal');
    for (const a of report.anomalies) {
      const cells = [
        a.refId,
        `${a.location}${a.gpsLat != null ? `\n${fmtGps(a.gpsLat, a.gpsLon)}` : ''}`,
        fmtTemp(a.tMax),
        fmtTemp(a.tMin),
        fmtTemp(a.baseline),
        a.deltaT == null ? '—' : `${a.deltaT > 0 ? '+' : ''}${a.deltaT.toFixed(1)}`,
        SEVERITY_LABELS[a.severity] ?? a.severity,
        CLASSIFICATION_LABELS[a.classification] ?? a.classification,
      ];
      doc.setFontSize(7.5);
      const wrapped = cells.map((cell, i) =>
        doc.splitTextToSize(cell, cols[i].w - 3) as string[],
      );
      const rowH = Math.max(...wrapped.map((wl) => wl.length)) * 3.4 + 2.5;
      if (y + rowH > pageH - margin) {
        doc.addPage();
        y = margin + 4;
        drawTableHeader();
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5); // header set 8pt; rows were wrapped at 7.5pt
      }
      let x = margin + 1.5;
      for (let i = 0; i < wrapped.length; i++) {
        doc.text(wrapped[i], x, y);
        x += cols[i].w;
      }
      y += rowH;
      doc.setDrawColor(210, 210, 210);
      doc.setLineWidth(0.15);
      doc.line(margin, y - 2, margin + contentW, y - 2);
    }
    y += 3;

    // Findings detail
    for (const a of report.anomalies) {
      if (!a.finding.trim() && !a.recommendation.trim()) continue;
      checkPage(14);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.text(`${a.refId} — Finding`, margin, y);
      y += 4.5;
      if (a.finding.trim()) paragraph(a.finding, 9);
      if (a.recommendation.trim()) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        checkPage(6);
        doc.text('Recommendation:', margin, y);
        y += 4.5;
        paragraph(a.recommendation, 9);
      }
    }
  }

  // ---- Action plan ----
  heading(`${sec++}. Action Plan & Repair Prioritization`);
  if (report.actionPlan.trim()) {
    paragraph(report.actionPlan);
  } else {
    paragraph('No action plan recorded.');
  }
  // Priority summary derived from severity grades
  const high = report.anomalies.filter((a) => a.severity === 'high');
  const medium = report.anomalies.filter((a) => a.severity === 'medium');
  const low = report.anomalies.filter((a) => a.severity === 'low');
  if (report.anomalies.length > 0) {
    paragraph(
      `Priority summary: ${high.length} high-severity (immediate corrective action), ` +
        `${medium.length} medium-severity (schedule repair), ` +
        `${low.length} low-severity (monitor).`,
      9,
    );
  }

  // Page footers
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 140);
    doc.text(`Page ${p} of ${pages}`, pageW - margin, pageH - 8, { align: 'right' });
    if (report.propertyAddress.trim()) {
      doc.text(report.propertyAddress, margin, pageH - 8);
    }
  }

  return new Uint8Array(doc.output('arraybuffer'));
}

// ============================================================================
// RTF export
// ============================================================================

function rtfEscape(text: string): string {
  let out = '';
  // Iterate UTF-16 code units (not code points): RTF's \uN escape is signed
  // 16-bit, so astral characters must be emitted as their surrogate pair.
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    const code = text.charCodeAt(i);
    if (ch === '\\') out += '\\\\';
    else if (ch === '{') out += '\\{';
    else if (ch === '}') out += '\\}';
    else if (ch === '\n') out += '\\line ';
    else if (code > 127) {
      const signed = code > 32767 ? code - 65536 : code;
      out += `\\u${signed}?`;
    } else {
      out += ch;
    }
  }
  return out;
}

/** Byte → two-char hex lookup (hot path for multi-MB embedded images). */
const HEX_LUT = Array.from({ length: 256 }, (_, i) => i.toString(16).padStart(2, '0'));

/** Convert a PNG/JPEG data URL to an RTF \pict group. */
function dataUrlToRtfPict(dataUrl: string, widthTwips: number, heightTwips: number): string {
  const [meta, b64] = dataUrl.split(',', 2);
  if (!b64) return '';
  const isPng = meta.includes('image/png');
  const binary = atob(b64);
  const parts: string[] = [];
  for (let i = 0; i < binary.length; i++) {
    parts.push(HEX_LUT[binary.charCodeAt(i)]);
    if (i % 64 === 63) parts.push('\n');
  }
  const type = isPng ? '\\pngblip' : '\\jpegblip';
  return `{\\pict${type}\\picwgoal${widthTwips}\\pichgoal${heightTwips}\n${parts.join('')}}`;
}

export function buildReportRtf(
  report: ThermalReport,
  images: ReportImages,
  extras: ReportExtras = {},
): string {
  const parts: string[] = [];
  parts.push(
    '{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Helvetica;}{\\f1 Courier New;}}' +
      '{\\colortbl;\\red20\\green60\\blue110;\\red200\\green60\\blue40;\\red110\\green110\\blue110;}',
  );

  const title = (text: string) =>
    parts.push(`{\\pard\\sa200\\b\\fs40\\cf1 ${rtfEscape(text)}\\par}`);
  const heading = (text: string) =>
    parts.push(`{\\pard\\sb240\\sa120\\b\\fs28\\cf1 ${rtfEscape(text)}\\par}`);
  const sub = (text: string) =>
    parts.push(`{\\pard\\sb120\\sa60\\b\\fs22 ${rtfEscape(text)}\\par}`);
  const para = (text: string) => {
    if (!text.trim()) return;
    parts.push(`{\\pard\\sa120\\fs20 ${rtfEscape(text)}\\par}`);
  };
  const kv = (key: string, value: string) =>
    parts.push(`{\\pard\\sa60\\fs20{\\b ${rtfEscape(key)}: }${rtfEscape(value || '—')}\\par}`);

  title('Thermal Inspection Report');
  parts.push(
    `{\\pard\\sa200\\fs16\\cf3 Generated by Open DroneLog${appVersion() ? ` v${appVersion()}` : ''} \\u183? DJI Thermal SDK\\par}`,
  );

  let sec = 1;

  heading(`${sec++}. Header Data`);
  kv('Property Address', report.propertyAddress);
  kv('Inspection Date', report.inspectionDate);
  kv('Weather Conditions', report.weatherConditions);
  kv('Inspector Name', report.inspectorName);

  if (report.summary.trim()) {
    heading(`${sec++}. Summary`);
    para(report.summary);
  }

  if ((report.linkedFlights ?? []).length > 0) {
    heading(`${sec++}. Flight Operations (DJI)`);
    for (const f of report.linkedFlights) {
      sub(f.displayName || `Flight ${f.id}`);
      if (f.startTime) kv('Date', f.startTime);
      if (f.droneModel) {
        kv('Drone', `${f.droneModel}${f.aircraftName ? ` (${f.aircraftName})` : ''}`);
      }
      kv('Duration', fmtDuration(f.durationSecs));
      kv('Distance', fmtMeters(f.totalDistance));
      if (f.maxAltitude != null) kv('Max altitude', `${f.maxAltitude.toFixed(0)} m`);
      if (f.maxSpeed != null) kv('Max speed', `${f.maxSpeed.toFixed(1)} m/s`);
      if (f.homeLat != null && f.homeLon != null) {
        kv('Home position', `${f.homeLat.toFixed(6)}, ${f.homeLon.toFixed(6)}`);
      }
      if (f.photoCount != null) kv('Photos', String(f.photoCount));
    }
  }

  if (extras.orthoDataUrl || report.orthomosaicLink.trim()) {
    heading(`${sec++}. Orthomosaic (Agisoft Metashape)`);
    if (extras.orthoDataUrl) {
      // ~16cm wide (9072 twips), height per the true aspect ratio capped at ~23cm
      const aspect = extras.orthoAspect && extras.orthoAspect > 0 ? extras.orthoAspect : 0.66;
      let wTw = 9072;
      let hTw = Math.round(wTw * aspect);
      if (hTw > 12960) {
        hTw = 12960;
        wTw = Math.round(hTw / aspect);
      }
      parts.push(`{\\pard\\sa60 ${dataUrlToRtfPict(extras.orthoDataUrl, wTw, hTw)}\\par}`);
      if (extras.orthoLabel) {
        parts.push(`{\\pard\\sa120\\fs16\\cf3 ${rtfEscape(extras.orthoLabel)}\\par}`);
      }
    }
    if (report.orthomosaicLink.trim()) {
      para(report.orthomosaicLink);
    }
  }

  heading(`${sec++}. Thermal Imaging Log & Comparative Matrix`);
  if (report.imagingLog.length === 0) para('No imaging entries.');
  report.imagingLog.forEach((entry: ReportImageEntry, i: number) => {
    sub(`${i + 1}. ${entry.caption || 'Imaging pair'}`);
    const pair = images[entry.id] ?? { thermal: null, visual: null };
    // ~7.5cm wide each (4252 twips), 4:3
    const w = 4252;
    const h = 3189;
    const cells: string[] = [];
    cells.push(pair.visual ? dataUrlToRtfPict(pair.visual, w, h) : '(no visual image)');
    cells.push(pair.thermal ? dataUrlToRtfPict(pair.thermal, w, h) : '(no thermal image)');
    parts.push(`{\\pard\\sa60\\fs18\\cf3 Visual (Zoom/Wide)\\tab\\tab Thermal (Infrared)\\par}`);
    parts.push(`{\\pard\\sa120 ${cells[0]} ${cells[1]}\\par}`);
    if (entry.lrfData.trim()) {
      kv('LRF / Range Data', entry.lrfData);
    }
  });

  heading(`${sec++}. Thermal Anomaly Log`);
  if (report.anomalies.length === 0) {
    para('No anomalies recorded.');
  } else {
    for (const a of report.anomalies) {
      sub(`${a.refId} — ${SEVERITY_LABELS[a.severity] ?? a.severity} severity`);
      kv('Location', a.location || '—');
      if (a.gpsLat != null) kv('Geotag', fmtGps(a.gpsLat, a.gpsLon));
      kv(
        'Temperatures',
        `Tmax ${fmtTemp(a.tMax)} · Tmin ${fmtTemp(a.tMin)} · Baseline ${fmtTemp(a.baseline)}` +
          (a.deltaT != null ? ` · ΔT ${a.deltaT > 0 ? '+' : ''}${a.deltaT.toFixed(1)} °C` : ''),
      );
      kv('Classification', CLASSIFICATION_LABELS[a.classification] ?? a.classification);
      if (a.finding.trim()) {
        kv('Finding', a.finding);
      }
      if (a.recommendation.trim()) {
        kv('Recommendation', a.recommendation);
      }
    }
  }

  heading(`${sec++}. Action Plan & Repair Prioritization`);
  para(report.actionPlan.trim() || 'No action plan recorded.');
  const high = report.anomalies.filter((a: ReportAnomalyEntry) => a.severity === 'high').length;
  const medium = report.anomalies.filter((a: ReportAnomalyEntry) => a.severity === 'medium').length;
  const low = report.anomalies.filter((a: ReportAnomalyEntry) => a.severity === 'low').length;
  if (report.anomalies.length > 0) {
    para(
      `Priority summary: ${high} high-severity (immediate corrective action), ${medium} medium-severity (schedule repair), ${low} low-severity (monitor).`,
    );
  }

  parts.push('}');
  return parts.join('\n');
}

// ============================================================================
// Save helpers
// ============================================================================

/** Save binary/text content via Tauri dialog (desktop) or browser download. */
export async function saveReportFile(
  defaultName: string,
  content: Uint8Array | string,
  filterName: string,
  extension: string,
): Promise<boolean> {
  const isWeb = import.meta.env.VITE_BACKEND === 'web';
  if (!isWeb) {
    try {
      const { save } = await import('@tauri-apps/plugin-dialog');
      const path = await save({
        defaultPath: defaultName,
        filters: [{ name: filterName, extensions: [extension] }],
      });
      if (!path) return false;
      const fs = await import('@tauri-apps/plugin-fs');
      if (typeof content === 'string') {
        await fs.writeTextFile(path, content);
      } else {
        await fs.writeFile(path, content);
      }
      return true;
    } catch (e) {
      console.error('Tauri save failed, falling back to browser download:', e);
    }
  }
  // Browser fallback
  const blob =
    typeof content === 'string'
      ? new Blob([content], { type: 'application/rtf' })
      : new Blob([content as BlobPart], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = defaultName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
  return true;
}
